# Generated by Django 5.2 on 2025-05-07 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(help_text='e.g., Oak Tree, Dandelion, Tall Fescue Grass', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Notes about the sighting, habitat, etc.')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_urls', models.TextField(blank=True, help_text='URLs of images from Supabase, one per line.')),
                ('is_native', models.BooleanField(blank=True, help_text='Is this species native to this location?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
